### ISSUE TITLE
License Issues

### ISSUE THREAD

**Issue by lights0123** [mrpiggypigpig/Hackra#3]
In the license at https://github.com/mrpiggypigpig/Hackra/blob/master/LICENSE you specify that you are using the MIT license. In the wiki page, you specify that "You may make libraries for Hackra, but they are then copyright mrpiggypigpig." This is not allowed by the license, stated by
<pre>
to deal
<b>in the Software without restriction</b>, including without limitation the rights
to use, copy, <b>modify</b>, merge, publish, distribute, sublicense, and/or sell
copies of the Software
</pre>

**Comment by mrpiggypigpig** [comment]
Solved
